FROM mysql:8.0

ADD ./scripts/dobavitelj.sql /docker-entrypoint-initdb.d/dobavitelj.sql
ADD ./scripts/gsm.sql /docker-entrypoint-initdb.d/gsm.sql
ADD ./scripts/trgovina.sql /docker-entrypoint-initdb.d/trgovina.sql
ADD ./scripts/wikileaks.sql /docker-entrypoint-initdb.d/wikileaks.sql