# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: szitnik/opb-mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Geslo.01

  phpmyadmin:
    image: szitnik/opb-phpmyadmin:4.8
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: Geslo.01
      PMA_HOST: mysql
    ports:
      - 8080:80
